class Autogenerated {
  List<Data>? data;
  Links? links;
  Meta? meta;
  Jsonapi? jsonapi;

  Autogenerated({this.data, this.links, this.meta, this.jsonapi});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    links = json['links'] != null ? new Links.fromJson(json['links']) : null;
    meta = json['meta'] != null ? new Meta.fromJson(json['meta']) : null;
    jsonapi =
        json['jsonapi'] != null ? new Jsonapi.fromJson(json['jsonapi']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    if (this.links != null) {
      data['links'] = this.links!.toJson();
    }
    if (this.meta != null) {
      data['meta'] = this.meta!.toJson();
    }
    if (this.jsonapi != null) {
      data['jsonapi'] = this.jsonapi!.toJson();
    }
    return data;
  }
}

class Data {
  String? type;
  Attributes? attributes;
  String? id;
  Links? links;

  Data({this.type, this.attributes, this.id, this.links});

  Data.fromJson(Map<String, dynamic> json) {
    type = json['type'];
    attributes = json['attributes'] != null
        ? new Attributes.fromJson(json['attributes'])
        : null;
    id = json['id'];
    links = json['links'] != null ? new Links.fromJson(json['links']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['type'] = this.type;
    if (this.attributes != null) {
      data['attributes'] = this.attributes!.toJson();
    }
    data['id'] = this.id;
    if (this.links != null) {
      data['links'] = this.links!.toJson();
    }
    return data;
  }
}

class Attributes {
  String? deviceId;
  String? createdBy;
  String? updatedBy;
  String? createdAt;
  int? status;
  String? fiberCode;
  Null? deletedAt;
  String? userId;
  String? updatedAt;

  Attributes(
      {this.deviceId,
      this.createdBy,
      this.updatedBy,
      this.createdAt,
      this.status,
      this.fiberCode,
      this.deletedAt,
      this.userId,
      this.updatedAt});

  Attributes.fromJson(Map<String, dynamic> json) {
    deviceId = json['device_id'];
    createdBy = json['created_by'];
    updatedBy = json['updated_by'];
    createdAt = json['created_at'];
    status = json['status'];
    fiberCode = json['fiber_code'];
    deletedAt = json['deleted_at'];
    userId = json['user_id'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['device_id'] = this.deviceId;
    data['created_by'] = this.createdBy;
    data['updated_by'] = this.updatedBy;
    data['created_at'] = this.createdAt;
    data['status'] = this.status;
    data['fiber_code'] = this.fiberCode;
    data['deleted_at'] = this.deletedAt;
    data['user_id'] = this.userId;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class Links {
  String? self;

  Links({this.self});

  Links.fromJson(Map<String, dynamic> json) {
    self = json['self'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['self'] = this.self;
    return data;
  }
}

class Meta {
  int? count;

  Meta({this.count});

  Meta.fromJson(Map<String, dynamic> json) {
    count = json['count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['count'] = this.count;
    return data;
  }
}

class Jsonapi {
  String? version;

  Jsonapi({this.version});

  Jsonapi.fromJson(Map<String, dynamic> json) {
    version = json['version'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['version'] = this.version;
    return data;
  }
}